/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef, useMemo } from "react";
import { useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";

export function Character({ animation, color, ghost, ...props }) {
  const group = useRef();
  const { scene, materials, animations } = useGLTF("/models/character.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);

  // Clone material per instance; ghost = translucent blue-white
  const mat = useMemo(() => {
    const m = materials.Material.clone();
    if (ghost) {
      m.color.set("#aaccff");
      m.transparent = true;
      m.opacity = 0.42;
      m.depthWrite = false;
    } else if (color) {
      m.color.set(color);
    }
    return m;
  }, [materials.Material, color, ghost]);

  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="fall_guys">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="body"
            geometry={nodes.body.geometry}
            material={mat}
            skeleton={nodes.body.skeleton}
            castShadow={!ghost}
            receiveShadow={!ghost}
          />
          <skinnedMesh
            name="eye"
            geometry={nodes.eye.geometry}
            material={mat}
            skeleton={nodes.eye.skeleton}
            castShadow={!ghost}
            receiveShadow={!ghost}
          />
          <skinnedMesh
            name="hand-"
            geometry={nodes["hand-"].geometry}
            material={mat}
            skeleton={nodes["hand-"].skeleton}
            castShadow={!ghost}
            receiveShadow={!ghost}
          />
          <skinnedMesh
            name="leg"
            geometry={nodes.leg.geometry}
            material={mat}
            skeleton={nodes.leg.skeleton}
            castShadow={!ghost}
            receiveShadow={!ghost}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/character.glb");
